import { JetBrains_Mono } from 'next/font/google';
import './globals.css';

// components
import Header from '@/components/Header';
import PageTransition from '@/components/PageTransition';
import StairTransition from '@/components/StairTransition';

const jetBrains_Mono = JetBrains_Mono({ 
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  variable: '--font-jetBrainsMono'
 });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetBrains_Mono.variable}>
      <Header/>
      <StairTransition/>
      <PageTransition>
        {children}
      </PageTransition>
      </body>
    </html>
  );
}

// Using var(--font-jetBrains_Mono)
// Why Use var():
// var(--font-jetBrains_Mono) retrieves the value of the custom property 
// --font-jetBrains_Mono.
// It allows you to define the font in one place and use it throughout your CSS.